### ISSUE TITLE
Houston 3D Map View

### ISSUE THREAD

**Issue by JonathanC8** [TeleIO/Telemachus-1#7]
the 3d map view is just a block screen for some reason anyone know a fix?

**Comment by samamstar** [comment]
I'm not sure why this has happened, but it appears at some point the files that run that view were made non-functional. If you download the original mod [https://github.com/KSP-Telemachus/Telemachus/releases](here) you can copy the javascript files from ..\Telemachus\Plugins\PluginData\Telemachus\houston\assets to the same place in your current gamedata folder. Desired file should be 3dmap.js . You should probably copy navigation.js as well, since that screen is broken as well

**Comment by dsolmann** [comment]
Thx for the fix, I'll embed it to next release!

**Comment by Stork42** [comment]
Looks like this issue has come back up. I've tried going back to older versions of the Houston mod and grabbing other versions of the 3dmap.js file and they did not seem to fix the black box. 3D maps show a black box with no content inside.
